project:
  type: website
  output-dir: docs
  render:
    - code/dispersal-analysis.qmd
    - code/export-data.qmd
    - code/functions.qmd
    - data.qmd
    - "!manuscript/"

website:
  title: "Southern Elephant Seal Pup Dispersal Analysis"
  navbar:
    left:
      - href: data.qmd
        text: Home
      - text: "Code"
        menu:
          - code/dispersal-analysis.qmd
          - code/export-data.qmd
          - code/functions.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    toc: true
    embed-resources: false