remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: "Southern Elephant Seal Pup Dispersal Analysis"
description: "Code documentation for tracking analysis"
author: "Dahlia Foo"

# Navigation
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/dahliasan/ses-pup-dispersal
